# Generated by Django 6.0.7 on 2026-08-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('breeder', 'Breeder'), ('owner', 'Dog Owner')], default='owner', max_length=20),
        ),
    ]
