# Generated by Django 6.0.7 on 2026-08-01 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DogProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age_years', models.PositiveIntegerField()),
                ('age_months', models.PositiveIntegerField(default=0, help_text='Age in months (0-11)')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('city', models.CharField(help_text='City/Location for proximity matching', max_length=100)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Weight in Kg', max_digits=4, null=True)),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='Fully Vaccinated')),
                ('medical_history', models.TextField(blank=True, help_text='Vaccination details or health notes')),
                ('kci_registered', models.BooleanField(default=False, verbose_name='KCI Registered')),
                ('kci_number', models.CharField(blank=True, help_text='Official KCI Registration Number', max_length=50, null=True)),
                ('lineage_details', models.TextField(blank=True, help_text='Pedigree lineage or champion bloodline details')),
                ('previous_litters', models.PositiveIntegerField(default=0, help_text='Number of past litters')),
                ('mating_terms', models.CharField(choices=[('stud_fee', 'Stud Fee'), ('want_puppy', 'Want Puppy (Pick of Litter)'), ('negotiable', 'Negotiable')], default='negotiable', max_length=20)),
                ('shelter_provider', models.CharField(choices=[('my_place', 'Arranged by me (At my place)'), ('other_place', 'Arranged by the mating partner'), ('negotiable', 'Negotiable')], default='negotiable', help_text='Shelter/Location arrangement preference', max_length=20)),
                ('willing_to_travel', models.BooleanField(default=False, help_text='Owner willing to travel for mating')),
                ('bio', models.TextField(blank=True, help_text='Temperament and behavior description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dog_photos/')),
                ('is_available', models.BooleanField(default=True, help_text='Available for breeding/mating inquiries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
