# Generated by Django 6.0.7 on 2026-08-02 05:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_phone_number_dogprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='dogprofile',
            name='willing_to_travel',
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='barking_level_rating',
            field=models.PositiveIntegerField(default=2, help_text='Vocal/Barking tendencies (0=Quiet, 5=Highly Vocal)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='dog_friendly_rating',
            field=models.PositiveIntegerField(default=3, help_text='Friendliness with other dogs (0=Very Unfriendly, 5=Very Friendly)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='energy_level_rating',
            field=models.PositiveIntegerField(default=3, help_text='Energy & Drive Level (0=Calm/Lazy, 5=Hyperactive/Working Drive)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='human_friendly_rating',
            field=models.PositiveIntegerField(default=3, help_text='Friendliness with strangers/humans (0=Very Reserved, 5=Very Friendly)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='travel_range',
            field=models.CharField(choices=[('none', 'Not willing to travel (Local pickup/meet only)'), ('0-5', 'Within 0 - 5 km'), ('5-20', 'Within 5 - 20 km'), ('20-50', 'Within 20 - 50 km'), ('50+', '50+ km (Statewide / Long distance)'), ('negotiable', 'Negotiable / Flexible')], default='0-5', max_length=20),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lbs', 'lbs')], default='kg', max_length=5),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='breed',
            field=models.CharField(choices=[('Beagle', 'Beagle'), ('Boxer', 'Boxer'), ('Bulldog', 'Bulldog'), ('Cocker Spaniel', 'Cocker Spaniel'), ('Dachshund', 'Dachshund'), ('Doberman Pinscher', 'Doberman Pinscher'), ('French Bulldog', 'French Bulldog'), ('German Shepherd', 'German Shepherd'), ('Golden Retriever', 'Golden Retriever'), ('Great Dane', 'Great Dane'), ('Labrador Retriever', 'Labrador Retriever'), ('Pomeranian', 'Pomeranian'), ('Poodle', 'Poodle'), ('Pug', 'Pug'), ('Rottweiler', 'Rottweiler'), ('Shih Tzu', 'Shih Tzu'), ('Siberian Husky', 'Siberian Husky'), ('Other', 'Other / Crossbreed')], default='Labrador Retriever', max_length=100),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='shelter_provider',
            field=models.CharField(choices=[('my_place', 'Arranged by me (At my place)'), ('other_place', 'Arranged by the mating partner'), ('negotiable', 'Negotiable')], default='negotiable', max_length=20),
        ),
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dog_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.dogprofile')),
            ],
        ),
    ]
