# Generated by Django 6.0.7 on 2026-08-02 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dogprofile_photo_remove_dogprofile_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='barking_level_rating',
            field=models.PositiveIntegerField(default=2, help_text='Vocal/Barking tendencies (1 to 5 Stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_friendly_rating',
            field=models.PositiveIntegerField(default=3, help_text='Friendliness with other dogs (1 to 5 Stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='energy_level_rating',
            field=models.PositiveIntegerField(default=3, help_text='Energy & Drive Level (1 to 5 Stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='human_friendly_rating',
            field=models.PositiveIntegerField(default=3, help_text='Friendliness with strangers/humans (1 to 5 Stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
