# Generated by Django 6.0.7 on 2026-08-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dogprofile_barking_level_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogprofile',
            name='barking_level_rating',
        ),
    ]
