# Generated by Django 6.0.7 on 2026-08-03 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_dogprofile_barking_level_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='kci_document',
            field=models.FileField(blank=True, null=True, upload_to='kci_documents/'),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='stud_fee_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Amount in ₹', null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='age_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_friendly_rating',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='energy_level_rating',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='human_friendly_rating',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='is_vaccinated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='kci_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='kci_registered',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='lineage_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='previous_litters',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
