# Generated by Django 6.0.7 on 2026-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dogprofile_kci_document_dogprofile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='breed_type',
            field=models.CharField(choices=[('Pure Breed', 'Pure Breed'), ('Cross Breed', 'Cross Breed')], default='purebred', max_length=20),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='secondary_breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
