# Generated by Django 6.0.7 on 2026-08-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dogprofile_breed_type_dogprofile_secondary_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='breed',
            field=models.CharField(default='Labrador Retriever', max_length=100),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='breed_type',
            field=models.CharField(choices=[('purebred', 'Purebred'), ('crossbreed', 'Crossbreed / Mix')], default='purebred', max_length=20),
        ),
    ]
