# Generated by Django 6.0.7 on 2026-09-13 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_veterinaryclinic_chatmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='age_months',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='age_years',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
