# Generated by Django 6.0.7 on 2026-09-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_dogprofile_age_months_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['match', 'timestamp'], name='core_chatme_match_i_f3b7be_idx'),
        ),
        migrations.AddIndex(
            model_name='dogprofile',
            index=models.Index(fields=['approval_status', 'is_available'], name='core_dogpro_approva_76c4c3_idx'),
        ),
        migrations.AddIndex(
            model_name='dogprofile',
            index=models.Index(fields=['city'], name='core_dogpro_city_404aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='dogprofile',
            index=models.Index(fields=['breed'], name='core_dogpro_breed_c33390_idx'),
        ),
        migrations.AddIndex(
            model_name='dogprofile',
            index=models.Index(fields=['gender'], name='core_dogpro_gender_93ad40_idx'),
        ),
        migrations.AddIndex(
            model_name='dogprofile',
            index=models.Index(fields=['-created_at'], name='core_dogpro_created_09aab3_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['sender', 'status'], name='core_matchr_sender__c50d99_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['receiver', 'status'], name='core_matchr_receive_185eac_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['target_dog', 'status'], name='core_matchr_target__604cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['-created_at'], name='core_matchr_created_4751f4_idx'),
        ),
        migrations.AddIndex(
            model_name='veterinaryclinic',
            index=models.Index(fields=['city'], name='core_veteri_city_534001_idx'),
        ),
        migrations.AddIndex(
            model_name='veterinaryclinic',
            index=models.Index(fields=['state'], name='core_veteri_state_d858a1_idx'),
        ),
        migrations.AddIndex(
            model_name='veterinaryclinic',
            index=models.Index(fields=['is_24x7_emergency'], name='core_veteri_is_24x7_f07933_idx'),
        ),
        migrations.AddIndex(
            model_name='veterinaryclinic',
            index=models.Index(fields=['-rating'], name='core_veteri_rating_54cfcb_idx'),
        ),
    ]
