# Generated by Django 6.0.7 on 2026-09-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='location_address',
            field=models.CharField(blank=True, help_text='General neighborhood or locality', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='dogprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='core_dogpro_latitud_85d4f0_idx'),
        ),
    ]
