# Generated by Django 6.0.7 on 2026-09-19 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_dogprofile_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='has_brucellosis_clearance',
            field=models.BooleanField(default=False, help_text='Brucellosis PCR negative lab test clearance'),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='last_deworming_date',
            field=models.DateField(blank=True, help_text='Most recent internal parasite deworming date', null=True),
        ),
        migrations.AddField(
            model_name='dogprofile',
            name='vaccination_record',
            field=models.FileField(blank=True, help_text='Official vaccination booklet or Rabies certificate', null=True, upload_to='health_documents/'),
        ),
        migrations.CreateModel(
            name='ReportListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake_profile', 'Fake Profile / Stolen Dog Photos'), ('fraudulent_kci', 'Fraudulent / Altered KCI Certificate'), ('underage_breeding', 'Underage / Inhumane Breeding Practices'), ('suspicious_user', 'Commercial Puppy Mill / Suspicious Commercial Activity'), ('other', 'Other Policy or Animal Welfare Violation')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('reported_dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.dogprofile')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', '-created_at'], name='core_report_is_reso_8fc190_idx')],
            },
        ),
    ]
