# Generated by Django 6.0.7 on 2026-09-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_dogprofile_has_brucellosis_clearance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlisting',
            name='reason',
            field=models.CharField(choices=[('underage', 'Underage Canine (<18 Months)'), ('puppy_mill', 'Commercial Puppy Mill / Unethical Breeding'), ('fake_kci', 'Fake or Tampered KCI Certificate'), ('health_concern', 'Unhealthy / Sick Canine / Fraudulent Vaccination'), ('inappropriate_content', 'Misleading or Inappropriate Photos'), ('spam', 'Commercial Spam / Advertisement'), ('other', 'Other Policy or Animal Welfare Violation')], max_length=30),
        ),
    ]
