# Generated by Django 6.0.7 on 2026-09-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_reportlisting_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['match', 'is_read'], name='core_chatme_match_i_e90bde_idx'),
        ),
    ]
