# Generated by Django 6.0.7 on 2026-09-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_chatmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dogprofile',
            index=models.Index(fields=['state'], name='core_dogpro_state_65b130_idx'),
        ),
        migrations.AddIndex(
            model_name='dogprofile',
            index=models.Index(fields=['approval_status', 'is_available', 'city'], name='core_dogpro_approva_59cbf6_idx'),
        ),
        migrations.AddIndex(
            model_name='dogprofile',
            index=models.Index(fields=['approval_status', 'is_available', 'breed'], name='core_dogpro_approva_b08f62_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['sender', 'receiver', 'status'], name='core_matchr_sender__67bff1_idx'),
        ),
    ]
